config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "musics#index"
  resources :users, only: [:index, :new, :create, :show, :update]
  resources :groups do
    resources :musics
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [
      {id: 0, name: '--'},
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
      {id: 0, name: '--'},
      {id: 1, name: 'ロック'}, {id: 2, name: 'Jポップ'}, {id: 3, name: 'Kポップ'},
      {id: 4, name: 'ヒップホップ'}, {id: 5, name: 'ジャズ'}, {id: 6, name: 'ブルース'},
      {id: 7, name: 'ソウル'}, {id: 8, name: 'R&B'}, {id: 9, name: 'カントリー'},
      {id: 10, name: 'レゲエ'}, {id: 11, name: 'ダンスミュージック'}, {id: 12, name: 'テクノ'},
      {id: 13, name: 'パンクロック'}, {id: 14, name: 'ヘヴィーメタル'}, {id: 15, name: 'ラップ'},
      {id: 16, name: 'オペラ'}, {id: 17, name: 'ラテン'}, {id: 18, name: 'フォーク'},
      {id: 19, name: 'クラシック'}, {id: 20, name: 'オルタナティブ'}, {id: 21, name: 'ハウス'},
      {id: 22, name: 'シャンソン'}, {id: 23, name: 'ディスコ'}, {id: 24, name: 'ゴスペル'}
  ]
end

app/models/group.rb
class Group < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :area
  belongs_to_active_hash :year

  has_many :user_groups
  has_many :users, through: :user_groups
  has_many :musics
  
  mount_uploader :image, ImageUploader
end

app/models/music.rb
class Music < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :genre

  belongs_to :group

  mount_uploader :file, AudioFileUploader
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_groups
  has_many :groups, through: :user_groups
  mount_uploader :image, ImageUploader
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/year.rb
class Year < ActiveHash::Base
  self.data = [
      {id: 0, name: '--'},
      {id: 1, name: '2020'}, {id: 2, name: '2019'}, {id: 3, name: '2018'},
      {id: 4, name: '2017'}, {id: 5, name: '2016'}, {id: 6, name: '2015'},
      {id: 7, name: '2014'}, {id: 8, name: '2013'}, {id: 9, name: '2012'},
      {id: 10, name: '2011'}, {id: 11, name: '2010'}, {id: 12, name: '2009'},
      {id: 13, name: '2008'}, {id: 14, name: '2007'}, {id: 15, name: '2006'},
      {id: 16, name: '2005'}, {id: 17, name: '2004'}, {id: 18, name: '2003'},
      {id: 19, name: '2002'}, {id: 20, name: '2001'}, {id: 21, name: '2000'},
      {id: 22, name: '1999'}, {id: 23, name: '1998'}, {id: 24, name: '1997'},
      {id: 25, name: '1996'}, {id: 26, name: '1995'}, {id: 27, name: '1994'},
      {id: 28, name: '1993'}, {id: 29, name: '1992'}, {id: 30, name: '1991'},
      {id: 31, name: '1990'}
  ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :introduce, :image])
    end
end

app/controllers/companys_controller.rb
class CompanysController < ApplicationController

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.create(group_params)
    redirect_to current_user 
  end

  def edit
    @group = Group.find(params[:id]) 
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_path
    else
      redirect_to edit_group_path
    end
  end
  
  private

  def group_params
    params.require(:group).permit(:image, :group_name, :area_id, :homepage_url, :year_id, user_ids: [])
  end


end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController

  def index
    @musics = Music.all.limit(20).order(id: "DESC")
  end

  def new
    @musics = Music.new
  end

  def create
    @music = Music.create(music_params)
    redirect_to root_path
  end

  def show
    @group = Group.find(params[:group_id])
    @music = @group.musics.find(params[:id])
  end

  def edit
  end

  def update
  end

private

  def music_params
    params.require(:musics).permit(:image, :title, :file, :text, :genre).merge(group_id: params[:group_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    return nil if params[:keyword] == ""
    @users = User.where(['nickname LIKE ?', "%#{params[:keyword]}%"]).where.not(id: current_user.id).limit(10)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    current_user.update(user_params)
    redirect_to user_path
  end

private

  def user_params
    params.require(:user).permit(:image, :nickname, :email, :introduce, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companys_helper.rb
module CompanysHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companys/edit.html.haml
.company__edit
  .company__edit__box
    .company__edit__box__name
      企業名
    .company__edit__box__menmber
      所属従業員名
    .company__edit__box__product
      主に扱う商品
    .company__edit__box__address
      企業住所
    .company__edit__box__homepage
      企業サイト
    .company__edit__box__business
      業種
    .company__edit__box__email
      メールアドレス
    .company__edit__box__phone
      企業の電話番号
    .company__edit__box__image
      企業イメージ

app/views/companys/new.html.haml
.company__new
  .company__new__box
    .company__new__box__name
      企業名
    .company__new__box__menmber
      所属従業員名
    .company__new__box__product
      主に扱う商品
    .company__new__box__address
      企業住所
    .company__new__box__homepage
      企業サイト
    .company__new__box__business
      業種
    .company__new__box__email
      メールアドレス
    .company__new__box__phone
      企業の電話番号
    .company__new__box__image
      企業イメージ

app/views/companys/show.html.haml
.company__new
  .company__new__box
    .company__new__box__name
      企業名
    .company__new__box__menmber
      所属従業員名
    .company__new__box__product
      主に扱う商品
    .company__new__box__address
      企業住所
    .company__new__box__homepage
      企業サイト
    .company__new__box__business
      業種
    .company__new__box__email
      メールアドレス
    .company__new__box__phone
      企業の電話番号
    .company__new__box__image
      企業イメージ

app/views/groups/edit.html.haml
.group__edit
  .group__edit--top
    = render "/share/top_bar"
  .group__edit--sidelist
    = render "/share/sidelist"

  .group__edit--title
    グループ編集
  .group__edit__box
    = form_with model: @group, class: "group__edit__box--form", local: true do |f|
      = f.hidden_field "group[user_ids][]", value: current_user.id
      .group__edit__box__list
        .group__edit__box__list__image
          .group__edit__box__list__image--inner
            %label
              %img#preview
                = f.file_field :image, class: "hidden", style: "display: none;"
                .arrow-left
                  = fa_icon "chevron-left", class: "arrow-left__icon"
                = image_tag "#{@group.image}"
        .group__edit__box__list__name
          グループ名:
          .group__edit__box__list__name--inner
            = f.text_field :group_name
        .group__edit__box__list__menmber
        
          .addmember__field
            .addmember__field--left
              %label.addmember__label{for: "addmember__plus"} メンバーを追加
            .addmember__field--right
              .addmember__search
                %input#user-search-field.addmember__input{placeholder: "メンバー検索", type: "text"}
              #user-search-result
          .addmember__field
            .addmember__field--left
              %label.addmember__label{for: "addmember__list"} メンバー：
            .addmember__field--right
              #addmember__groups.js-add-user
                .addmember__group.js-group-member
                  %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
                  %p.addmember__group--users= current_user.nickname
              - @group.users.each do |user|
                - if current_user.nickname != user.nickname
                  .addmember__group.js-group-member
                    %input{name: "group[user_ids][]", type: "hidden", value: user.id}
                    %p.addmember__group--users
                      = user.nickname
                    %a.user-search-remove.addmember__btn.addmember__btn--remove.js-remove-btn
                      削除

        .group__edit__box__list__active--area
          主な活動地域:
          .group__edit__box__list__active--area--inner
            = f.collection_select :area_id, Area.all, :id, :name
        .group__edit__box__list__homepage
          ホームページ:
          .group__edit__box__list__homepage--inner
            = f.text_field :homepage_url, class: "group__edit__homepage"
        .group__edit__box__list__since
          Since
          .group__edit__box__list__since--inner
            = f.collection_select :year_id, Year.all, :id, :name
        .group__edit__box__list__submit
          = f.submit "グループ編集", class: "group__edit__submit"
          
  .back
    = link_to "BACK", group_path, class: "back"

  .footer
    = render "/share/footer"

app/views/groups/new.html.haml
.group
  .group__top
    = render "/share/top_bar"
  .group__sidelist
    = render "/share/sidelist"

  .group__title
    グループ新規作成
  .group__new
    = form_with model: @group, class: "group__new__form", local: true do |f|
      .group__new__box
        クリックでイメージを追加
        .group__new__box__image
          = f.label :image, for: "upload_image" do
            %img#preview
              = f.file_field :image, class: "group__image", id: "upload_image"

      .group__new__box__under
        .group__new__box__under__name
          グループ名：
          .group__new__box__under__name--inner
            = f.text_field :group_name, class: "group__name"

        .group__new__box__under__menmber
          .addmember__field__on
            .addmember__field__on--left
              %label.addmember__label{for: "addmember__plus"} メンバーを追加
            .addmember__field__on--right
              .addmember__search
                %input#user-search-field.addmember__input{placeholder: "メンバー検索", type: "text"}
              #user-search-result
          .addmember__field
            .addmember__field--left
              %label.addmember__label{for: "addmember__list"} メンバー：
            .addmember__field--right
              #addmember__groups.js-add-user
                .addmember__group.js-group-member
                  %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
                  %p.addmember__group--users= current_user.nickname
              - @group.users.each do |user|
                - if current_user.nickname != user.nickname
                  .addmember__group.js-group-member
                    %input{name: "group[user_ids][]", type: "hidden", value: user.id}
                    %p.addmember__group--users
                      = user.nickname
                    %a.user-search-remove.addmember__btn.addmember__btn--remove.js-remove-btn
                      削除
                      
        .group__new__box__under__active--area
          主な活動地域：
          .group__new__box__under__active--area--inner
            = f.collection_select :area_id, Area.all, :id, :name
        .group__new__box__under__homepage
          ホームページ：
          .group__new__box__under__homepage--inner
            = f.text_field :homepage_url, class: "group__homepage"
        .group__new__box__under__since
          Since：
          .group__new__box__under__since--inner
            = f.collection_select :year_id, Year.all, :id, :name
        .group__new__box__under__submit
          = f.submit "グループ登録", class: "group__submit"
          .back
            = link_to "BACK", :back, clss: "back-btn"
.footer
  = render "/share/footer"

app/views/groups/show.html.haml
.group__show
  .group__show__top
    = render "share/top_bar"
  .group__show__sidelist
    = render "share/sidelist"

  .group__show__title
    所属グループ
  .group__show__list
    .group__show__list__box
      .group__show__list__box__upper
        .group__show__list__box__upper__image
          = image_tag "#{@group.image}"
        .group__show__list__box__upper--inner
          メニュー
          .group__show__list__box__upper--inner__music
            = link_to "楽曲登録", new_group_music_path(@group.id), class: "new_music"
          .group__show__list__box__upper--inner__edit
            = link_to "グループ編集", edit_group_path, class: "edit_group"
      .group__show__list__box__under
        .group__show__list__box__under__name
          グループ名：
          .group__show__list__box__under__name--inner
            = @group.group_name
        .group__show__list__box__under__member
          メンバー：
          .group__show__list__box__under__member--inner
            - @group.users.each do |user|
              = user.nickname
        .group__show__list__box__under__active--area
          主な活動地域：
          .group__show__list__box__under__active--area--inner
            = @group.area.name
        .group__show__list__box__under__homepage
          ホームページ：
          .group__show__list__box__under__homepage--inner
            = @group.homepage_url
        .group__show__list__box__under__disc
          今までの楽曲：
          .group__show__list__box__under__disc--inner
            - @group.musics.reverse.each do |music|
              .group__musics
                = link_to music.title, group_music_path(@group.id, music.id)
  .back
    = link_to "BACK", current_user, class: "back"
.footer
  = render "/share/footer"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TMusicOffer
    = csrf_meta_tags
    = csp_meta_tag
    %script{src: "https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link(rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css")
  %body
    = yield

app/views/musics/edit.html.haml
.edit__music
  .edit__music__format
    .edit__music__format__title
      楽曲名
    .edit__music__format__genre
      音楽ジャンル
    .edit__music__format__image
      No Image
    .edit__music__format__int
      楽曲の紹介

app/views/musics/index.html.haml
.music
  .top
    = render "/share/top_bar"

  .middle
    = render "/share/sidelist"

  .main
    = render "/share/music_list"


.footer
  = render "/share/footer"

app/views/musics/new.html.haml
.new__music
  .new__music--top
    = render "/share/top_bar"
  .new__music--sidebar
    = render "/share/sidelist"
    
  .new__music__title
    新楽曲登録
  .new__music__format
    = form_with model: @group, url: group_musics_path, class: "music__new__form", local: true do |f|
      .new__music__format__main
        = f.fields_for :musics do |music|
          .new__music__format__main__image
            楽曲イメージ：
            .new__music__format__main__image--inner
              = music.label :image, for: "upload_image" do
                %img#preview
                  = music.file_field :image, class: "music__image", id: "upload_image"
          .new__music__format__main__title
            楽曲名：
            .new__music__format__main__title--inner
              = music.text_field :title, class: "music__title"
          .new__music__format__main__genre
            音楽ジャンル：
            .new__music__format__main__genre--inner
              = f.collection_select :genre, Genre.all, :id, :name
          .new__music__format__main__mp3url
            楽興URL：
            .new__music__format__main__mp3url--inner
              = music.file_field :file, class: "music__file"
          .new__music__format__main__introduce
            楽曲の紹介：
            .new__music__format__main__introduce--inner
              = music.text_area :text, class: "music__introduce"
          .new__music__format__main__submit
            = music.submit "新楽曲を登録する", class: "music__submit"
            = link_to "BACK", :back, class: "back"

.footer
  = render "/share/footer"

app/views/musics/show.html.haml
.music__show
  .music__show__top
    = render "share/top_bar"
  .music__show__sidelist
    = render "share/sidelist"

  .music__show__title
    楽曲詳細
  .music__show__file
    .music__show__file__group
      = @group.group_name
    .music__show__file__under
      .music__show__file__under__name
        = @music.title
      .music__show__file__under__mp3url
        = @music.file
  .music__show__list
    .music__show__list__image
      = image_tag "#{@music.image}"
    .music__show__list__right
      .music__show__list__right__genre
      .music__show__list__right__text
        = @music.text

.back
  = link_to "BACK", :back

.footer
  = render "/share/footer"

app/views/share/_footer.html.haml
.footer__text
  since 2020

app/views/share/_music_list.html.haml
- @musics.each do |music|
  .main__box
    .main__box__contents
      .main__box__contents__left
        .main__box__contents__left__image
          = image_tag "#{music.image}"
      .main__box__contents__right
        .main__box__contents__right__text
          音楽の紹介文概要：
          .main__box__contents__right__text--inner
            = music.title
        .main__box__contents__right__music--url
          楽曲を再生する： 
          .main__box__contents__right__music--url--inner
            %audio{preload: "none", src: "#{music.file}"}
              :javascript
                audiojs.events.ready(function() {
                  var as = audiojs.createAll();
                });
              
        .main__box__contents__right__more
          = link_to "詳しく見る", group_music_path(music.group_id, music.id)

app/views/share/_sidelist.html.haml
.middle__list
  .middle__list__search
    検索枠
  .middle__list__favorite
    お気に入りリスト
  .middle__list__genre
    音楽ジャンル

app/views/share/_top_bar.html.haml
.top__logo
  .top__logo--box
    = link_to root_path do
      T-Music Offer
.top__set
  .top__set__list
    - if user_signed_in?
      .top__set__list--user
        = link_to current_user.nickname, current_user, class: "user_status"
      .top__set__list--group
        = link_to "新規グループ追加", new_group_path, class: "group_show"
      .top__set__list--find
        提供企業を探す
    - else 
      .top__set__list--user
        = link_to "新規ユーザー登録", new_user_registration_path, class: "user_status"
      .top__set__list--group
        = link_to "ログイン", new_user_session_path, class: "group_show"

app/views/users/show.html.haml
.user
  .user__top
    = render "/share/top_bar"
  .user__side
    = render "/share/sidelist"
    
  %ul.user__profile
    .user__profile__box
      .user__profile__box__image
        - if current_user.image.present?
          .user__profile__box__image--icon
            = image_tag "#{current_user.image}"
        - else
          NO IMAGE
    %li.user__profile__list
      .user__profile__list__name
        名前：
        .user__profile__list__name--inner
          = current_user.nickname
      .user__profile__list__groups
        所属グループ：
        .user__profile__list__groups--inner
          .user__profile__list__groups--inner--part
            - if current_user.groups.present?
              - current_user.groups.each do |group|
                .user__to__group
                  = link_to group_path(group.id) do
                    = image_tag "#{group.image}" , class: "user__group__image"
                    .user__group--name
                      = group.group_name
            - else
              NO BILONGING GROUP
      .user__profile__list__text
        紹介文：
        .user__profile__list__text--inner
          .user__profile__list__text--inner--part
            - if current_user.present?
              = current_user.introduce
            - else
              NO INTRODUCTION
      .user__profile__list__email
        メールアドレス：
        .user__profile__list__email--inner
          = current_user.email
      .user__profile__list__recomend
        推しアーティスト：
        .user__profile__list__recomend--inner
          NO LIST
      .user__profile__list__edit
        .user__profile__list__edit--btn
          = fa_icon "arrow-left", class: "icon" 
          編集

    //edit機能
    %li.user__profile__list.show
      = form_with model: @user, class: "user__profile__list__edit__page", local: true do |f|
        .user__profile__list__edit__page__box
          .user__profile__list__edit__page__box--upper
            名前：
            .user__profile__list__edit__page__box--upper--name
              = f.text_field :nickname, class: "name_edit", id: "name_edit", placeholder: "name"
          .user__profile__list__edit__page__box--midle
            紹介文：
            .user__profile__list__edit__page__box--midle--text
              = f.text_area :text, class: "text_edit", id: "text_edit", placeholder: "#{current_user.introduce}"
          .user__profile__list__edit__page__box--under
            メールアドレス：
            .user__profile__list__edit__page__box--under--email
              = f.text_field :email, class: "email_edit", id: "email_edit", placeholder: "email"
          .user__profile__list__edit__page__box--submit
            = f.submit "編集", class: "edited"
      .user__profile__list__edit        
        .user__profile__list__edit--btn
          = fa_icon "arrow-right", class: "icon" 
          中止

  .user__logout
    = link_to "ログアウト", destroy_user_session_path, class: "logout", method: :delete

.footer
  = render "/share/footer"